### ISSUE TITLE
Block page states page is not blocked...

### ISSUE THREAD

**Issue by iroQuai** [WaLLy3K/Pi-hole-Block-Page#9] opened 2017-03-04 23:49 UTC
I've started with a fresh Raspbian image, installed pi-hole and directly this block page. Added some lists, added the landing.php and changed some values in the phbp.ini file. I get something unexpected: whenever I visit a blocked page, I get this message:

![This site is not blocked.
Please flush your DNS cache and/or restart your browser ](https://cloud.githubusercontent.com/assets/7004624/23583146/1bf0e7ea-013c-11e7-8f54-8a192e410977.png)

Obviously this is not true, since I can't visit that website.
I flushed DNS logs, restarted browsers, computers, modums and the pi itself. The problem stays and is consistent on different devices. 

Any idea what to do?

PS. the debug log from that same site states that this site is not on any adlist, which is not true. Same result with other blocked sites...

```
`Server/OS: Raspbian GNU/Linux 8 (jessie)
› OS Uptime: 00:30:32
› Task Load: 0, 0.03, 0.08 (3/59 active)
› CPU usage: 8% (Temp: 33c, Cores: 1)
› RAM usage: 26% (114 MB of 435 MB used)
› PHP usage: 256 KB (128M limit)
› P-H usage: 462,665 domains (10/206 blocked)
› PHBP info: v2.2.1 (RCI: v2.2.1, 0a6e236c)
› PHBP conf: Passwd: 1, WL: 1, Updates: 1
› Adlists.list: 26 blocklists
› Queryads.php: 0 results ()
› Doubleclick.net: 0 lists (-1)
› Generated in: 0.59s

User Config Array
(
    [landPage] => landing.php
    [selfDomain] => none
    [blockImage] => https://wally3k.github.io/style/blocked.svg
    [customIcon] => http://pi.hole/admin/img/favicon.png
    [customLogo] => https://wally3k.github.io/style/phv.svg
    [adminEmail] => user@redacted.com
    [allowWhitelist] => true
    [checkUpdates] => true
)
```

**Comment by iroQuai** [comment] 2017-03-06 19:38
tried to deinstall, did `pihole -r` and reinstalled phbp. same problem still there!

**Comment by levinuss** [comment] 2017-03-07 20:30
Same Problem here. I replaced all the adlist links in the phbp.ini with the exact links from my custom adlists.list and tried with several domains. Getting the same message. When I set another CSS file (the one from the pi-hole project itself) I get "This domain is in 0 of 11 Lists...". How to solve this?
Additional I got some problems with the https forwarding of Https Everywhere but I don't think that thats a problem that can be solved.

**Comment by WaLLy3K** [comment] 2017-03-07 23:38
I'm really sorry about how long it's taken me to reply to this!

I'm currently running the FTL development version of Pi-hole which has broken PHBP's functionality, and I'm awaiting the arrival of a Pi Zero to do troubleshooting on with a fresh version of Raspbian/Pi-hole - so this limits what troubleshooting I can do.

Having said that, could either of you head to the following link and copy/paste the output? [http://pi.hole/admin/scripts/pi-hole/php/queryads.php?domain=doubleclick.net&exact](http://pi.hole/admin/scripts/pi-hole/php/queryads.php?domain=doubleclick.net&exact) (and preferably, the other confirm if they're seeing the same output?)

Thanks!

**Comment by iroQuai** [comment] 2017-03-08 00:20
First I got a no authorisation message. After I logged in in the admin page and tried again, I got this:
```

data: ::: /etc/pihole/list.0.raw.githubusercontent.com.domains (1 results)
data: 0.0.0.0 doubleclick.net
data: 
data: 

data: ::: /etc/pihole/list.1.mirror1.malwaredomains.com.domains (0 results)
data: 
data: 

data: ::: /etc/pihole/list.10.v.firebog.net.domains (0 results)
data: 
data: 

data: ::: /etc/pihole/list.11.v.firebog.net.domains (0 results)
data: 
data: 

data: ::: /etc/pihole/list.12.v.firebog.net.domains (0 results)
data: 
data: 

data: ::: /etc/pihole/list.13.raw.githubusercontent.com.domains (0 results)
data: 
data: 

data: ::: /etc/pihole/list.14.v.firebog.net.domains (0 results)
data: 
data: 

data: ::: /etc/pihole/list.15.s3.amazonaws.com.domains (1 results)
data: doubleclick.net
data: 
data: 

data: ::: /etc/pihole/list.16.mirror1.malwaredomains.com.domains (0 results)
data: 
data: 

data: ::: /etc/pihole/list.17.hosts-file.net.domains (0 results)
data: 
data: 

data: ::: /etc/pihole/list.18.hosts-file.net.domains (0 results)
data: 
data: 

data: ::: /etc/pihole/list.19.hosts-file.net.domains (0 results)
data: 
data: 

data: ::: /etc/pihole/list.2.sysctl.org.domains (1 results)
data: 127.0.0.1	 doubleclick.net
data: 
data: 

data: ::: /etc/pihole/list.20.mirror.cedia.org.ec.domains (0 results)
data: 
data: 

data: ::: /etc/pihole/list.21.www.malwaredomainlist.com.domains (0 results)
data: 
data: 

data: ::: /etc/pihole/list.23.openphish.com.domains (0 results)
data: 
data: 

data: ::: /etc/pihole/list.24.ransomwaretracker.abuse.ch.domains (0 results)
data: 
data: 

data: ::: /etc/pihole/list.25.zeustracker.abuse.ch.domains (0 results)
data: 
data: 

data: ::: /etc/pihole/list.3.zeustracker.abuse.ch.domains (0 results)
data: 
data: 

data: ::: /etc/pihole/list.4.s3.amazonaws.com.domains (0 results)
data: 
data: 

data: ::: /etc/pihole/list.5.s3.amazonaws.com.domains (1 results)
data: doubleclick.net
data: 
data: 

data: ::: /etc/pihole/list.6.hosts-file.net.domains (1 results)
data: 127.0.0.1	doubleclick.net
data: 
data: 

data: ::: /etc/pihole/list.7.raw.githubusercontent.com.domains (0 results)
data: 
data: 

data: ::: /etc/pihole/list.8.raw.githubusercontent.com.domains (1 results)
data: 127.0.0.1 doubleclick.net
data: 
data: 

data: ::: /etc/pihole/list.9.s3.amazonaws.com.domains (1 results)
data: doubleclick.net
data: 
data: 

data: ::: /etc/pihole/list.preEventHorizon (1 results)
data: doubleclick.net
data: 
data: ::: /etc/pihole/blacklist.txt does not exist
data: 
data: 

data: 

```

**Comment by levinuss** [comment] 2017-03-08 06:14
Similar here.

```
data: ::: /etc/pihole/list.0.raw.githubusercontent.com.domains (1 results)
data: 

data: 0.0.0.0 doubleclick.net
data: 
data: 

data: ::: /etc/pihole/list.1.mirror1.malwaredomains.com.domains (0 results)
data: 

data: 
data: 

data: ::: /etc/pihole/list.10.localhost.domains (1 results)
data: 

data: doubleclick.net
data: 
data: 

data: ::: /etc/pihole/list.2.sysctl.org.domains (1 results)
data: 

data: 127.0.0.1	 doubleclick.net
data: 
data: 

data: ::: /etc/pihole/list.3.zeustracker.abuse.ch.domains (0 results)
data: 

data: 
data: 

data: ::: /etc/pihole/list.4.s3.amazonaws.com.domains (0 results)
data: 

data: 
data: 

data: ::: /etc/pihole/list.5.s3.amazonaws.com.domains (1 results)
data: 

data: doubleclick.net
data: 
data: 

data: ::: /etc/pihole/list.6.hosts-file.net.domains (1 results)
data: 

data: 127.0.0.1	doubleclick.net
data: 
data: 

data: ::: /etc/pihole/list.7.raw.githubusercontent.com.domains (0 results)
data: 

data: 
data: 

data: ::: /etc/pihole/list.8.raw.githubusercontent.com.domains (0 results)
data: 

data: 
data: 

data: ::: /etc/pihole/list.9.raw.githubusercontent.com.domains (0 results)
data: 

data: 
data: 

data: ::: /etc/pihole/list.preEventHorizon (1 results)
data: 

data: doubleclick.net
data: 
data: ::: /etc/pihole/blacklist.txt does not exist
data: 
data: 

data: 
```

**Comment by WaLLy3K** [comment] 2017-03-08 06:22
> Similar here.

Also a "no authorisation" message? If that's the case, I have a fair idea what's happening now, I just need to test it on something that isn't my main Pi-hole install.

I'll update this ticket once I know more (which should *hopefully* be before the end of the week depending on shipping) - until then, I'd recommend either [uninstalling PHBP](https://github.com/WaLLy3K/Pi-hole-Block-Page#uninstall), or ignoring it depending on how much of a concern it is to you.

Thanks again for reporting this, and I'm sorry this isn't something I'm able to fix quickly!

**Comment by iroQuai** [comment] 2017-03-08 06:25
Please, stop apologizing! Your offering an fantastic add-on to pi-hole for
free and from my experience your very responsive and thorough - end of the
week is fine!

Op wo 8 mrt. 2017 07:22 schreef WaLLy3K <notifications@github.com>:

**Comment by levinuss** [comment] 2017-03-08 08:46
I agree that you don't have to apologize. Its a great add-on and your support is also great so far.
I had also a "no authorisation" message until I logged into the PiHole WI and refreshed the page after that.

**Comment by frankied210** [comment] 2017-03-09 17:18
I just installed this and spent all day yesterday troubleshooting it until I finally came here to submit a ticket and discovered it’s not just me.
Looking forward to resolution and seeing this work as intended.
Kudos to you and your work on this!!!

**Comment by frankied210** [comment] 2017-03-09 22:52
I came up with a work around.

Commented out password requirement in queryads.php

sudo nano /var/www/html/admin/scripts/pi-hole/php/queryads.php

Before:
require "password.php";
if(!$auth) die("Not authorized");

After:
//require "password.php";
//if(!$auth) die("Not authorized");

**Comment by WaLLy3K** [comment] 2017-03-09 23:54
Another option (that admittedly I didn't think of) would be to disable Pi-hole's password, using `pihole -a -p` in Terminal.

This has two effects worth considering:
* Your Pi-hole admin panel will be less secure from people on your network (Or even accessible externally if you port forward 80)
* You will be unable to whitelist pages from the block page

I've spoken to the Pi-hole dev team, and they're reverting the changes that have caused the issue to occur - hopefully, everything should sort itself out with the next public release!

**Comment by WaLLy3K** [comment] 2017-03-14 11:29
Pi-hole Admin Page v2.5.2 released an hour ago includes [fix #439](https://github.com/pi-hole/AdminLTE/pull/439), which should resolve this issue. Please make sure to run `pihole -up`, and it should take care of the rest.

**Comment by WaLLy3K** [comment] 2017-03-14 11:59
Didn't mean to close this as I need to confirm the fix works - will do so in the morning.

**Comment by frankied210** [comment] 2017-03-14 15:17
I did a reinstall of Pi-Hole and the block page.
Seems to be working 99%.
Only wildcard blacklisted don't come up with the correct block page. Not a big deal to me.
Another  issue I'm see is, the "This site is found in X of X lists:" is displayed without using the "More Info" button. (button actually shows More Info) I click the More Info button and the button changes to "Less Info" but the details are still shown. A second click of the button results in the list being hidden and the button changing back to "More Info" This is what I would expect to see on initial page load.

**Comment by WaLLy3K** [comment] 2017-03-14 21:46
Thanks for the update! I'll look into handling wildcard blocking (I forget about that feature, as I don't use it myself) and the More Info behaviour should be fixed with the next update as I've moved it away from using any JavaScript - users shouldn't be expected to have JavaScript run on untrusted domains in this day and age.

**Closed as completed by WaLLy3K** 2017-03-14 21:46 UTC
Labels: bug
